### Run the tests in IntellIj or reset DB info..


###     Player routes

### Create user - success case
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@alunos.isel.pt",
    "name" : "pedro3",
    "password" : "peelrooro"
}

### Create user - name already exists (call the success case) 
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@hotmail.com",
    "name" : "pedro3",
    "password" : "peelrooro"
}

### Create user - email already exists (call the success case)
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@alunos.isel.pt",
    "name" : "pedro33333",
    "password" : "peelrooro"
}

### Create user - blank name
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@alunos.isel.pt",
    "name" : "       ",
    "password" : "peelrooro"
}

### Create user - name length lower than 4 chars
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@alunos.isel.pt",
    "name" : "joe",
    "password" : "peelrooro"
}

### Create user - name length bigger than 50 chars
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a47718@alunos.isel.pt",
    "name" : "joejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoejoe",
    "password" : "peelrooro"
}

### Create user - email doesnt match email format
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a4771831313141",
    "name" : "adqldqlld",
    "password" : "peelrooro"
}

### Create user - password is blank
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a44039@gmail.com",
    "name" : "adqldqlld",
    "password" : "             "
}

### Create user - password smaller than 6 chars
POST http://localhost:9000/api/players
content-type: application/json

{
    "email" : "a44039@gmail.com",
    "name" : "adqldqlld",
    "password" : "abc"
}

### Fetch user - successfull case
GET http://localhost:9000/api/players/1008

### Fetch user - that doesnt exist
GET http://localhost:9000/api/players/130103103


###     Game Routes

### Create Game - Successful case
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "APEX LEGENDS",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

### Create Game - Repeat game name
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "APEX LEGENDS",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

### Create Game - Blank name
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "           ",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

### Create Game - Blank developer
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "Battlefield V",
    "developer" : "      ",
    "genres" : ["Shooter"]
}

### Create Game - empty genres
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "Battlefield V",
    "developer" : "Something",
    "genres" : []
}

### Create Game - duplicate genres
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "name" : "Battlefield V",
    "developer" : "Something",
    "genres" : ["Shooter", "Shooter"]
}

### Get Game By ID - Succesfull case
GET http://localhost:9000/api/games/id/107

### Get Game By ID - Invalid Game ID
GET http://localhost:9000/api/games/id/10713131

### Get Game By Name - Successfull case
GET http://localhost:9000/api/games/name/CS

###  Get Game By Name - Invalid Name
GET http://localhost:9000/api/games/name/CSSADASDADADADADADADADFAFGAFAFAFAFAFAFA

### Get List of Games - Successful case
POST http://localhost:9000/api/games/list
content-type : application/json

{
    "developer" : "Valve",
    "genres" : ["Shooter"]
}

### Get List of Games - blank developer
POST http://localhost:9000/api/games/list
content-type : application/json

{
    "developer" : "      ",
    "genres" : ["Shooter"]
}

### Get List of Games - empty genres list
POST http://localhost:9000/api/games/list
content-type : application/json

{
    "developer" : "Valve",
    "genres" : []
}

### Creating a Session - succesful case
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2024-04-03 18:00:00"
}

### Creating a Session - invalid game id
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107133131,
    "capacity" : 2,
    "date" : "2024-04-03 18:00:00"
}

### Creating a Session - invalid capacity
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : -1,
    "date" : "2024-04-03 18:00:00"
}

### Creating a Session - invalid date format
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2024-04-08:00:00"
}

### Creating a Session - invalid date (past date)
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2024-02-08 18:00:00"
}

### Add Player to Session (use session created in the succesful case)
PUT http://localhost:9000/api/sessions/10001/players
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb8

### Add Player to Session Again (use session created in the succesful case ), results in error
PUT http://localhost:9000/api/sessions/10001/players
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb8

### Get Session - succesful case
GET http://localhost:9000/api/sessions/10001

### Get Session - wrong session id
GET http://localhost:9000/api/sessions/10005313131

### Get list of sessions
POST http://localhost:9000/api/sessions/list
content-type:application/json

{
    "gid" : 107,
    "state" : "open",
    "date" : null,
    "pid" : null
}


### First Create A Session

POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2024-04-03 18:00:00"
}

### Update Session - Successful Case 
PUT http://localhost:9000/api/sessions/10006
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "capacity" : "3",
    "date" : "2025-04-04 18:00:00"
}

### Update Session - Not the Owner of the Session
PUT http://localhost:9000/api/sessions/10006
Authorization: Bearer 0b6b9396-b062-4803-a8bc-804849de85eb
content-type: application/json

{
    "capacity" : "3",
    "date" : "2025-04-04 18:00:00"
}

### Add 2 players and test if can reduce capacity

PUT http://localhost:9000/api/sessions/10006/players
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb8

### Add second player
PUT http://localhost:9000/api/sessions/10006/players
Authorization: Bearer fe9423b1-0951-4f17-9826-381b0532ce16

### Test 1 - Reduce Capacity

PUT http://localhost:9000/api/sessions/10006
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "capacity" : "2",
    "date" : "2025-04-04 18:00:00"
}

### Test 2 - Increase Capacity - Succesfull
PUT http://localhost:9000/api/sessions/10006
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "capacity" : "4",
    "date" : "2025-04-04 18:00:00"
}

### Create a session and test that cant update because session is ongoing
POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2024-03-27 13:25:40"
}

### Try to update a session 1 min later
PUT http://localhost:9000/api/sessions/10008
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "capacity" : 3,
    "date" : "2025-04-04 18:00:00"
}

### Update on a session that doesnt exist
PUT http://localhost:9000/api/sessions/1000310310
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "capacity" : 3,
    "date" : "2025-04-04 18:00:00"
}

### Session Deletion

### Create A Session for Testing

POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2025-03-27 13:25:40"
}


### Delete Session - Not the Owner 

DELETE http://localhost:9000/api/sessions/10011
Authorization: Bearer fe9423b1-0951-4f17-9826-381b0532ce16


### Deletion successful
DELETE http://localhost:9000/api/sessions/10011
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7


### Delete a session that does not exist
DELETE http://localhost:9000/api/sessions/10010313131
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7


### Delete player from session

### First create session

POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2025-03-27 13:25:40"
}

### Delete a player that isnt involved in the session
DELETE http://localhost:9000/api/sessions/10013/players
Authorization: Bearer 0b6b9396-b062-4803-a8bc-804849de85eb

### Delete a player from a session that doesnt exist
DELETE http://localhost:9000/api/sessions/100133/players
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7

### Delete the only player from a session is successful and also deletes the session

DELETE http://localhost:9000/api/sessions/10013/players
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7

### retrieve session
GET http://localhost:9000/api/sessions/10013


### Delete a player from a full/closed session

### First create a session

POST http://localhost:9000/api/sessions
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "gid" : 107,
    "capacity" : 2,
    "date" : "2025-03-27 13:25:40"
}

### Add a second player

PUT http://localhost:9000/api/sessions/10014/players
Authorization: Bearer fe9423b1-0951-4f17-9826-381b0532ce16

### Remove the second player should make the session open again

DELETE http://localhost:9000/api/sessions/10014/players
Authorization: Bearer fe9423b1-0951-4f17-9826-381b0532ce16

### Retrieve session afterwards

GET http://localhost:9000/api/sessions/10014

###     Authorization invalid token format - Game Creation
POST http://localhost:9000/api/games
Authorization: Bearer NOTOKEN
content-type: application/json

{
    "name" : "CoolGame",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

###     Authorization invalid token - Game Creation
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852fffffffff
content-type: application/json

{
    "name" : "CoolGame",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

###     Authorization no header - Game Creation
POST http://localhost:9000/api/games
content-type: application/json

{
    "name" : "CoolGame",
    "developer" : "Rampage",
    "genres" : ["Shooter"]
}

###     JSON mapping error
POST http://localhost:9000/api/games
Authorization: Bearer 3ad7db4b-c5a9-42ee-9094-852f94c57cb7
content-type: application/json

{
    "nowork" : 10310
}